# Generated by Django 5.2.1 on 2025-05-21 13:31

import MyWebApps.MyFirstApplication.models.Inscription
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.IntegerField(blank=True, null=True, unique=True)),
                ('names', models.CharField(max_length=155)),
                ('father_surname', models.CharField(max_length=155)),
                ('mother_surname', models.CharField(max_length=155)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cui', 'names', 'father_surname', 'mother_surname'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=155)),
                ('father_surname', models.CharField(max_length=155)),
                ('mother_surname', models.CharField(max_length=155)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['names', 'father_surname', 'mother_surname'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curriculum', models.IntegerField(choices=[(0, 'Sin Plan'), (2017, 'Plan 2017'), (2023, 'Plan 2023')], default=2017)),
                ('year', models.IntegerField(choices=[(0, 'Sin ano'), (1, '1er ano'), (2, '2do ano'), (3, '3er ano'), (4, '4to ano'), (5, '5to ano'), (6, '6to ano'), (7, '7mo ano')], default=0)),
                ('semester', models.IntegerField(choices=[(0, 'Sin semestre'), (1, 'I semestre'), (2, 'II semestre'), (3, 'III semestre'), (4, 'IV semestre'), (5, 'V semestre'), (6, 'VI semestre'), (7, 'VII semestre'), (8, 'VIII semestre'), (9, 'IX semestre'), (10, 'X semestre')], default=0)),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=25, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('theory_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('practice_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('laboratory_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('laboratory', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='MyFirstApplication.course')),
            ],
            options={
                'ordering': ['curriculum', 'year', 'semester', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('laboratory', models.CharField(choices=[('lab01', 'Laboratorio 01'), ('lab02', 'Laboratorio 02'), ('lab03', 'Laboratorio 03'), ('lab04', 'Laboratorio 04'), ('lab05', 'Laboratorio 05'), ('lab06', 'Laboratorio 06'), ('lab07', 'Laboratorio 07'), ('lab08', 'Laboratorio 08')], default='lab01', max_length=5)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.teacher')),
            ],
            options={
                'ordering': ['course', 'group', 'laboratory', 'capacity', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.student', validators=[MyWebApps.MyFirstApplication.models.Inscription.validate_even])),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.workload')),
            ],
            options={
                'ordering': ['workload', 'student', 'created'],
            },
        ),
        migrations.AddConstraint(
            model_name='workload',
            constraint=models.UniqueConstraint(fields=('course', 'group'), name='unique_workload'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('workload', 'student'), name='unique_inscription'),
        ),
    ]
